In [11]:
from PIL import Image
from numpy import asarray
from sklearn.naive_bayes import GaussianNB

In [28]:
# sample.png is the name of the image
# file and assuming that it is uploaded
# in the current directory or we need
# to give the path
image = Image.open('Sample.png')
  
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)

numpydata = asarray(image)
print(numpydata)

pilImage = Image.fromarray(numpydata)
print(type(pilImage))

image_file = image.convert('1') # convert image to black and white
image_file.save('result.png')

PNG
(400, 200)
RGB
[[[111  60   0]
  [116  65   0]
  [122  69   0]
  ...
  [ 97  47   0]
  [ 99  47   0]
  [100  49   0]]

 [[111  61   0]
  [118  65   0]
  [122  69   0]
  ...
  [ 97  47   0]
  [ 99  48   0]
  [100  49   0]]

 [[118  65   0]
  [122  69   0]
  [126  73   3]
  ...
  [ 98  48   0]
  [100  49   0]
  [100  49   0]]

 ...

 [[ 96  44   7]
  [ 95  43   6]
  [ 93  41   4]
  ...
  [225  80   3]
  [228  80   0]
  [229  78   0]]

 [[ 93  40   6]
  [ 90  37   5]
  [ 85  32   0]
  ...
  [226  81   4]
  [231  80   1]
  [232  79   1]]

 [[ 89  36   4]
  [ 84  31   0]
  [ 79  26   0]
  ...
  [228  81   4]
  [232  81   4]
  [233  80   2]]]
<class 'PIL.Image.Image'>


In [30]:
image_file = image.convert('1').resize((28, 28)) # convert image to black and white
image_file.save('Blresult.png')

In [40]:
image = Image.open('Blresult.png')
data = asarray(image)
print(data.shape)
model=GaussianNB()
model.fit([data[:,1]],[1])

(28, 28)


GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
model.predict()